import type { Metadata } from 'next'
import '@/app/styles/globals.css'
import { Providers } from '@/app/providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ko'>
      <head>
        <link rel='icon' href='/favicon.svg' type='image/svg+xml' />
      </head>
      <body className='font-pretendard'>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
